Update audio.md
system76/docs pull request #1005
Opened 2022-05-05 22:52 UTC by thomas-zimmerman

* Add sets of commands to restart `PipeWire` 
* Add commands to reinstall default PipeWire packages
* Update commands to reinstall default PulseAudio packages
* Add commands for PipeWire status and `pw-top`

2022-05-05 23:32 UTC, jacobgkau requested changes

2022-05-05 23:32 UTC, jacobgkau commented on content/audio.md
> +Sound settings or packages related to the sound system can become corrupt or broken. Many times, deleting the configuration files, reinstalling the sound-related packages, and starting the audio soft
I understand making the name of the audio software more generic, but was this supposed to change from reloading/restarting to just starting?

2022-05-05 23:32 UTC, jacobgkau commented on content/audio.md
> +If the system is not playing audio, first try restarting the Audio daemon:
`Audio` is not the name of anything and should not be capitalized.

2022-05-05 23:32 UTC, jacobgkau commented on content/audio.md
> +| `systemctl --user restart pulseaudio` | `systemctl --user restart restart wireplumber pipewire pipewire-pulse` |
Your pipewire restart command has the word `restart` twice, that will not work (systemctl thinks you're trying to restart a service called "restart" and doesn't find that service.)

2022-05-05 23:32 UTC, jacobgkau commented on content/audio.md
> +This set of commands first restarts the sound daemon and removes the users configuration for PulseAudio. If still using PulseAudio as a server, restarts the PulseAudio server that will create new def
In the first sentence, `users` should have an apostrophe.

In the second sentence, you're missing a subject in the clause after the comma.

2022-05-05 23:32 UTC, jacobgkau commented on content/audio.md
> +systemctl --user status wireplumber
This is checking WirePlumber, not PipeWire. There is a `pipewire.service` and a number of `pipewire-...` services that are separate from what you're referring to here. (It's fine if you've found WirePlumber to be the service that needs checked for errors, but the description for the command should reflect that.)

2022-05-05 23:32 UTC, jacobgkau commented on content/audio.md
> +If you would like to monitor PipeWire, run:
I'm not sure what this command is showing me, having just run it for the first time. A more specific description would be helpful.

2022-05-25 15:58 UTC, ahoneybun commented
I've fixed most of the comments but some I'd like to address at a later date so that we can get the PipeWire changes in as soon as possible.

2022-05-25 19:29 UTC, ahoneybun approved these changes
LGTM as a base for an update to this article. Provides helpful commands for PipeWire now instead of just commands for PulseAudio which do not work in 22.04 LTS+

2022-05-25 20:20 UTC, jacobgkau commented on content/audio.md
> +This set of commands first restarts the sound daemon and removes the user's configuration for PulseAudio. If still using PulseAudio as a server, restarts the PulseAudio server that will create new de
This is not a complete sentence. There is no subject in the clause after the comma.

2022-05-25 20:21 UTC, jacobgkau commented on content/audio.md
> +This command will reinstall the PipeWire packages:
Why did you include `the` in the second one of these sentences but not the first one?

2022-05-25 20:23 UTC, jacobgkau approved these changes

2022-05-26 15:55 UTC, merged