Create enable-wayland.md
system76/docs pull request #1017
Opened 2022-06-12 18:54 UTC by uncivilgentleman

I realized this isn't great documentation but it's hopefully better than nothing.

2022-06-13 15:02 UTC, jacobgkau requested changes
Wayland is disabled by default for a reason (it does not work as expected on all System76 hardware, and it is therefore not supported for the time being.) At the very least, an article like this would need to explain that this is unsupported (maybe with some examples of problems that can show up), and should include instruction for reverting back to Xorg. We may also want to consider making this be part of the Community Articles section since it is not something we want to endorse right now.

2022-06-17 19:55 UTC, storyaddict submitted a review, later dismissed
Approving this for the text. I'd like screenshots to be added in another PR after. 
I took some screenshots in a VM which I can add.

2022-06-17 20:20 UTC, jacobgkau requested changes

2022-06-17 20:20 UTC, jacobgkau commented on content/enable-wayland.md
> +Edit `/etc/gdm3/custom.conf` and comment out the line `WaylandEnable=false`. Save the file and restart your computer.
This doesn't explain what "commenting out" means, or how to edit this file with elevated privileges. These instructions are not sufficient.

2023-03-22 16:59 UTC, ahoneybun commented
@uncivilgentleman I'm closing this issue as it is stale but please do let us know if you have any questions about updating.

2023-03-22 16:59 UTC, closed without merging