Strengthening Disclaimer
system76/docs pull request #1034
Opened 2022-07-20 17:44 UTC by storyaddict

This PR Does the Following:

- Combines the "scope of support" section with the "disclaimer section." 
- Clarifies and strengthens the language around what System76 will/won't support.
- Gives an example of the kind of problems user may expect to encounter when running Windows on System76 hardware.

2022-07-20 17:46 UTC, cwsystem76 commented
While you're working on this, would it be possible to also update the Windows 11 section? It talks about TPM support, but not Secure Boot, which is the real sticking point. Our Coreboot systems have a TPM but not Secure Boot, and it's the latter that's the real issue.

2022-07-20 17:49 UTC, storyaddict commented
> While you're working on this, would it be possible to also update the Windows 11 section? It talks about TPM support, but not Secure Boot, which is the real sticking point. Our Coreboot systems have a TPM but not Secure Boot, and it's the latter that's the real issue.

I'm giving this a second pass to make those changes now.

2022-07-20 19:01 UTC, cwsystem76 commented
> Open Firmware systems to do support Secure Boot which is a requirement for Windows 11.

I think this is meant to be "do not support"?

2022-07-20 22:22 UTC, Ampersandstorm requested changes
I'm fine with these changes as long as this disclaimer doesn't conflict with statements in System76 marketing material, and falls in-line with Emma and Sam's support expectations. We don't want people thinking some warranty has been voided just because they tried to install Windows and now their system won't startup for whatever reason. I wonder if adding steps to restore Pop!_OS (or a link to an article showing how to install Pop!_OS) would be helpful.

2022-07-20 22:22 UTC, Ampersandstorm commented on content/windows.md
> +The contents of this support article are the **total extent of support and troubleshooting that System76 can provide for Windows.** Any troubleshooting or Windows support questions not covered in thi
Consider changing `Any troubleshooting or Windows support questions not covered in this article are outside the scope of System76 and should be referred to Microsoft.`

to:

`Any Windows-related support for System76 hardware not covered in this article is beyond the scope of support provided by System76. Please refer to Microsoft's [official troubleshooting documentation](https://support.microsoft.com/en-us) or other online resources.`

2022-12-27 14:23 UTC, ahoneybun approved these changes
LGTM

2022-12-27 17:46 UTC, n3m0-22 requested changes
The new changes look good. The three changes suggested still need to be addressed.

2022-12-27 18:36 UTC, n3m0-22 approved these changes
Looks good.

2022-12-27 19:12 UTC, merged