Update guides.md
system76/docs pull request #1124
Opened 2023-04-17 16:42 UTC by thomas-zimmerman

...with links to new tech-docs links

2023-04-17 17:39 UTC, n3m0-22 requested changes

2023-04-17 17:39 UTC, n3m0-22 commented on content/guides.md
> +| Darter Pro [(darp6)](https://tech-docs.system76.com/models/darp6/README.html) | Thelio Major [(thelio-major)](https://tech-docs.system76.com/models/thelio-major-intel-and-amd/README.html) |  Launch
The link for `Thelio Major [(thelio-major)]` should be changed to `Thelio Major [(thelio-major-r3)]`

2023-04-24 20:19 UTC, n3m0-22 requested changes

2023-04-24 20:19 UTC, n3m0-22 commented on content/guides.md
> +| Darter Pro [(darp7)](https://tech-docs.system76.com/models/darp7/README.html) | Thelio Major [(thelio-major-r2)](https://tech-docs.system76.com/models/thelio-major-r3/README.html) |
The Thelio Major link text shows `thelio-major-r2` but links to `thelio-major-r3`

2023-05-02 12:31 UTC, ahoneybun submitted a review, later dismissed

2023-05-02 14:29 UTC, n3m0-22 approved these changes
Looks good

2023-05-02 18:52 UTC, ahoneybun commented
I'm going to add the new serw13 and addw3 tech docs then we can review this again.

2023-05-02 18:57 UTC, ahoneybun approved these changes

2023-05-02 19:23 UTC, ahoneybun approved these changes

2023-05-02 19:46 UTC, n3m0-22 approved these changes
All text and links are correct now. Looks good.

2023-05-02 19:57 UTC, merged