Update driver software
system76/docs pull request #1127
Opened 2023-05-04 12:22 UTC by ahoneybun

This PR updates the Fedora and Arch sections for the system76 driver and software articles.

2023-05-04 17:51 UTC, thomas-zimmerman approved these changes
Looks good on Live preview.

2023-05-05 21:04 UTC, XV-02 requested changes
Some typo fixes needed, and also, the Fedora instructions in `content/system76-software.md` seem very out-of-order right now. We'll need to resolve that before we move forward.

2023-05-05 21:04 UTC, XV-02 commented on content/system76-software.md
> +sudo dnf install system76* firmware-manager
Doesn't this do exactly what lines 169-180 do? (section "System76 Firmware Manager in Fedora")

2023-05-05 21:04 UTC, XV-02 commented on content/system76-software.md
> +**NOTE:** After enabling the dkms systemd service for any of the DKMS packages you will need to reboot the system:
The previous instructions don't cover DKMS packages?

2023-05-08 16:17 UTC, ahoneybun commented on content/system76-driver.md
>  makepkg -srcif
We do not maintain the AUR package so we can't make this change, this works fine as it currently.

2023-05-09 21:09 UTC, thomas-zimmerman commented on content/system76-driver.md
>  makepkg -srcif
Double checking the live npm build this still looks good. While the update the PKGBUILD file would be nice, that will need to happen with the AUR maintainer.

2023-05-09 21:11 UTC, thomas-zimmerman submitted a review, later dismissed
Looks good to merge

2023-06-06 20:57 UTC, XV-02 approved these changes

2023-09-15 16:20 UTC, thomas-zimmerman approved these changes
I would like to get these changes out. NPM live view looks good.

2023-09-15 16:32 UTC, merged