Work on Issue 971
system76/docs pull request #1138
Opened 2023-05-25 18:02 UTC by ahoneybun

2023-05-25 18:38 UTC, n3m0-22 commented
Is this ready for review or are you still working on it? I'm still seeing the 404.

2023-05-25 19:00 UTC, ahoneybun commented
Should be fine, what 404?

2023-06-01 16:38 UTC, n3m0-22 approved these changes
I'm not sure why I had an issue the other day, but I am no longer seeing it. The rest of these changes look good to me.

2023-08-02 15:29 UTC, leviport requested changes

2023-08-02 18:10 UTC, jacobgkau commented on content/pop-incomplete-upgrade.md
> +You can Refresh the OS without losing user account information and data in the home directory. You can find out more about this option [here](/articles/pop-recovery)
Does that distinction matter in this context?

2023-08-02 18:21 UTC, leviport commented on content/pop-incomplete-upgrade.md
> +You can Refresh the OS without losing user account information and data in the home directory. You can find out more about this option [here](/articles/pop-recovery)
That's what I was thinking. Just a little extra specificity.

2023-08-02 18:28 UTC, leviport commented on content/pop-incomplete-upgrade.md
> +You can Refresh the OS without losing user account information and data in the home directory. You can find out more about this option [here](/articles/pop-recovery)
Thanks!

2023-08-02 18:38 UTC, jacobgkau commented on content/live-disk.md
> +If Pop!\_OS is installed and a Pop!\_OS live disk is used it can be used to Refresh the OS without losing user account information and data in the home directory. You can find out more about this opt
Done with fcaceb4.

2023-08-02 18:38 UTC, jacobgkau commented on content/pop-incomplete-upgrade.md
> +You can Refresh the OS without losing user account information and data in the home directory. You can find out more about this option [here](/articles/pop-recovery)
Done with fcaceb4.

2023-08-02 18:40 UTC, leviport approved these changes
:+1:

2023-08-03 19:16 UTC, thomas-zimmerman approved these changes
Nice updates. LGTM

2023-08-03 19:17 UTC, merged