Add section for tech docs and guides
system76/docs pull request #1145
Opened 2023-06-20 15:05 UTC by ahoneybun

Address feedback from a support ticket and helps promote tech-docs

2023-06-20 16:14 UTC, thomas-zimmerman approved these changes
LGTM

2023-06-21 22:19 UTC, leviport requested changes
I do have to agree with @Raikiri about the location of this being rather awkward since it's pretty unrelated to contacting us. I think it would be best to add a section in the "Before you open a ticket" article. The left column would _kinda_ work, but it still feels a bit awkward and out of place.

What do you think of adding a section to the "Before you open a ticket" article?

2023-06-22 01:13 UTC, Raikiri commented
Putting it into "Before you open a ticket" is basically putting into the last possible place somebody might want to check right before creating a ticket that says "I can't find your technical documentation". So no, I don't think it's a good place, I think the link needs to be in the topmost location in the navigation hierarchy, maybe even put it into the header:
![image](https://github.com/system76/docs/assets/1657728/18c43dbe-67d6-40ed-823f-415de7b0e4ba)


Honestly "Support articles" seems like a really logical place for the list of support articles to be.

2023-06-22 12:14 UTC, ahoneybun commented
@Raikiri that location would not be part of the docs project and instead with the web team so it's not an option at least from this PR.

2023-06-26 14:41 UTC, leviport commented
>Putting it into "Before you open a ticket" is basically putting into the last possible place somebody might want to check right before creating a ticket that says "I can't find your technical documentation". 

I meant that question for Aaron, but thanks for the input. My impression is that's pretty much the exact idea we were going for. This is a link to a support article that has various links to tech-docs for each model. I believe having that support article amongst the rest is still sufficient, but I agree with Aaron that it can probably be improved. Adding a link to a support article into the header for the whole site, next to a link to the list of support articles, is not something I'm super keen on. And we certainly wouldn't be able to get Marketing, Web, Sales, etc. on board with such a change either.

2023-07-03 09:12 UTC, Raikiri commented
Another thing I wanted to mention: if it's going to be named "Find Documentation For Your Model" among a million other articles, I expect it to be very hard to find: maybe it's a me problem, but when I want to repair my laptop, I never search for "Documentation", I search for "repair guide", "<model name> internal view", "disassembly", etc. "Documentation" strikes me as data sheets rather than a guide.

Pardon me if I sound too nitpicky and I don't really have a solution to this problem. I'm just providing you a data point of my own experience: since from my past experience I know that you guys have this documentation, after some struggle I do manage to find it every time I need it. But if I was on your page for the first time, a good chance I wouldn't be able to.

2023-07-03 15:54 UTC, leviport commented
>I search for "repair guide", " internal view", "disassembly", etc. 

That's a good point, and I think it'd be good to add those to the search terms for that article. "Components" and "guide" both bring it up, but adding more terms is easy enough.

2023-07-06 14:53 UTC, ahoneybun commented
@leviport @Raikiri I've made some changes so if you want to give this another review let me know.

2023-07-06 17:07 UTC, leviport commented on content/before-you-open-a-support-ticket.md
> + - disassembly
Should the keywords be in this article as well? It seems to me that it'd be better if they were only in the guides article

2023-07-06 17:15 UTC, leviport approved these changes

2023-07-06 17:16 UTC, leviport commented
(I just removed a stray space that was left over from where those keywords were deleted)

2023-07-07 01:39 UTC, Raikiri commented
I still can't find the documentation while searching for "repair guide" or "internal view". Even if I do stumble upon "Documentation for your model", it's not immediately obvious that it's what I'm looking for. But it's obviously better than none at all.

2023-08-01 20:09 UTC, ahoneybun commented
> I still can't find the documentation while searching for "repair guide" or "internal view". Even if I do stumble upon "Documentation for your model", it's not immediately obvious that it's what I'm looking for. But it's obviously better than none at all.

The keywords do not effect the search, it seems to be based on title and description.

2023-09-18 17:12 UTC, thomas-zimmerman approved these changes
Let's get this change live and see if this helps. Changes look fine on the live view.

2023-09-18 17:49 UTC, merged