Update linux gaming
system76/docs pull request #1175
Opened 2023-09-18 15:31 UTC by ahoneybun

This updates screenshots, text and other items for 22.04.

2023-09-20 21:24 UTC, leviport requested changes
Looks like a good update, but I have one nitpick

2023-09-20 21:24 UTC, leviport commented on content/linux-gaming.md
> +Once installed, use the Application button to search for and run <u>Steam</u>.
The button says "Applications", so I'm thinking Application should probably be plural to match the button, right?

2023-09-20 21:24 UTC, leviport commented on content/linux-gaming.md
> +Once installed, use the Application button to search for and run <u>Steam</u>.
The button says "Applications", so I'm thinking Application should probably be plural to match the button, right?

2023-09-20 21:24 UTC, leviport commented on content/linux-gaming.md
> +Once installed, use the Application button to search for and run <u>GameHub</u>.
The button says "Applications", so I'm thinking Application should probably be plural to match the button, right?

2023-09-20 21:29 UTC, leviport approved these changes

2023-09-21 17:43 UTC, garrettjwilke approved these changes

2023-09-21 17:53 UTC, merged