Update desktop-environment.md
system76/docs pull request #1190
Opened 2023-10-18 03:44 UTC by memachado

This addition offers users a more comprehensive solution for removing KDE and its associated packages. This enhancement aims to provide clearer and more user-friendly instructions for managing desktop environments on Pop!_OS.

2023-10-19 18:16 UTC, jacobgkau requested changes
The article shows how to install KDE by running `sudo apt install kde-standard`, which will install `kde-standard`'s dependencies. Running an `autoremove --purge kde-standard` will remove `kde-standard` and everything installed as a dependency of it. There's no reason why `kde-*` would be needed unless the user installed KDE via a different package/method.

The `kde-*` wildcard may uninstall more packages than intended; for example, if I installed the `kde-spectacle` program to use in GNOME, then I later installed `kde-standard`, running `sudo apt purge kde-*` will remove `kde-spectacle` even though it wasn't installed as part of the desktop environment.

Also, `purge` is actually less comprehensive than an `autoremove --purge` because `purge` will not remove dependencies by itself; it would require another `autoremove --purge` after it. (In this case, there is one immediately after it, but specifying `kde-standard` in that one after `kde-*` was already purged is redundant.) It's probably best to use `autoremove --purge` in all instances here.

I think there's a place for the wildcard/pattern-matching concept in this article, but it should be separated into a separate section for if the reader's forgotten which package(s) they manually installed.

Additionally, * wildcards aren't reliable; if you `touch kde-testing` and then try to run the `sudo apt purge kde-*` command in the same directory, you'll get an error that no `kde-testing` package is found, because that wildcard is matched to the filename rather than package names. Instead, `sudo apt purge '?name(^kde-)'` would do the same thing (remove packages starting with `kde-`), without running into issues in case of matching filenames.

2023-10-19 20:28 UTC, memachado commented
@jacobgkau  Thank you for the feedback and explanation. I did not consider those points prior to the PR. I'll run some more tests, if nothing goods come out, I drop the PR. Bye.

2023-10-19 22:12 UTC, memachado commented
@jackpot51 

To test the current example and documentation:

- Fresh installation
- Installed the KDE Standard as described in the docs
- Rebooted, logged in, and tested KDE
- Rebooted again, logged into GNOME
- "Removed" as described in the docs
- Rebooted and was able to log in again to the KDE environment because KDE was not uninstalled, hence my attempt to further enhance the docs.

The method in this PR was found on Stack Overflow, but I traced it to the old version of these docs.

Although the old/proposed method can remove unintended packages, the current method does not remove the necessary packages.

2023-10-20 00:14 UTC, jacobgkau commented
Thank you for the steps and elaborating on the issue. I can recreate that with `kde-standard`. I'm not quite sure what's going on yet, but I'll try to look into it a little further.

(Playing around with `-o APT::Autoremove::SuggestsImportant=0` and `-o APT::Autoremove::RecommendsImportant=0`, it looks like it might be other, preinstalled packages that suggest or recommend some of the KDE packages or their dependencies/recommendations. The former option removes too little and the latter option removes too much, though. `plasma-workspace` and `plasma-desktop` may be creating the issue between themselves, from what I'm seeing trying to use `aptitude why` on them.)

If we do stick with the wildcard option, we'll still want to use regex rather than the asterisk.

2023-10-20 04:45 UTC, memachado commented
> If we do stick with the wildcard option, we'll still want to use regex rather than the asterisk.

Still, the regex would need to be `sudo apt purge '?name(-kde-)'` because packages like `qml-module-org-kde-*`. And even after that some packages will remain.

Maybe change the example to another desktop environment, and include a warning about kde remaining packages after install? This way people can choose how to proceed.

2023-10-20 22:48 UTC, jacobgkau commented
> Maybe change the example to another desktop environment, and include a warning about kde remaining packages after install?

I don't see how removing the KDE example will help if that's one that we know currently has problems.

> Still, the regex would need to be `sudo apt purge '?name(-kde-)'` because packages like `qml-module-org-kde-*`. And even after that some packages will remain.

Actually, using the `^kde-` regex with `autoremove`, I do see `qml-module-org-kde-...` get removed even though it wouldn't be matched by that regex:

![image](https://github.com/system76/docs/assets/7199422/ab13c271-3674-4e48-a647-7a71ff7079c3)

With `autoremove`, we don't actually need to match every package we want to be uninstalled, we just need to match the ones that apt doesn't want to uninstall unless we tell it to.

2023-10-20 23:20 UTC, jacobgkau commented
I've tried to explain the example in a simple but effective way. I do think this is a valuable addition, so thanks for bringing it up.

2023-10-20 23:20 UTC, jacobgkau approved these changes

2023-10-21 00:08 UTC, memachado commented
> With autoremove, we don't actually need to match every package we want to be uninstalled, we just need to match the ones that apt doesn't want to uninstall unless we tell it to.

My bad. I used `sudo apt purge '?name(^kde-)'`  instead of `sudo apt autoremove --purce '?name(^kde-)'` . 

> I've tried to explain the example in a simple but effective way. I do think this is a valuable addition, so thanks for bringing it up. (Let me know if you see any issues with what I changed it to.)

Looks good to me. 

Thank you.

2023-12-14 17:47 UTC, ahoneybun approved these changes

2023-12-15 16:37 UTC, ahoneybun commented
@memachado is this ready to go with your latest changes?

2023-12-15 16:58 UTC, memachado commented
@ahoneybun Yes.

2023-12-15 17:04 UTC, merged