Update docking station article to list which devices support which USB-C features
system76/docs pull request #464
Opened 2020-09-18 22:43 UTC by nathandyer

Adds a chart that makes it easier for customers to determine which USB-C features are supported by their system.

2020-09-18 22:45 UTC, nathandyer commented
To see a better preview of the change:

![Screenshot from 2020-09-18 18-44-21](https://user-images.githubusercontent.com/6131358/93651299-067b7980-f9df-11ea-9446-371659543c5d.png)

2020-09-18 22:50 UTC, leviport commented on _articles/use-docking-station.md
> +<td style="height: 23px;">No</td>
darp5 does support USB-C charging. I use a 60W USB-C charger on the regular with my darp5.

2020-09-25 23:14 UTC, storyaddict requested changes
Change Darp5 to USB-C charging "yes." Per Leviport's feedback.

2020-10-02 23:10 UTC, ahoneybun approved these changes
LGTM

2020-10-02 23:11 UTC, merged