Update memory testing to use 'memtester'
system76/docs pull request #564
Opened 2021-02-26 22:05 UTC by thomas-zimmerman

2021-02-26 22:30 UTC, ahoneybun reviewed
Won't memtest86 have issues with Open Firmware?

2021-05-26 00:11 UTC, storyaddict requested changes

2021-05-26 00:11 UTC, storyaddict commented on _articles/hardware-failure.md
> +```
Shouldn't we specify to test their total RAM -4G?

2021-05-26 00:11 UTC, storyaddict commented on _articles/hardware-failure.md
> +This memory testcan take a number of hours. While this will not put all of memory under test, it will make any memory error much more likely to cause instability if it is not directly part of the tes
*missing space.

"This memory test can take..."

2021-06-11 20:24 UTC, storyaddict commented
Issue has been fixed in another PR.

2021-06-11 20:24 UTC, closed without merging