New Minecraft Installer + Optifine
system76/docs pull request #578
Opened 2021-03-21 23:21 UTC by kylerchin

2021-03-21 23:22 UTC, kylerchin commented
This was created in response to issue #527

2021-03-22 15:23 UTC, kolgza commented
I was the one who wrote the instructions on how to install the Flatpak version of Minecraft. I believe that we need to discuss whether we want new users to install Minecraft this way. At least, we need to have this discussion before the instructions to install the Flatpak version are outright removed.

2021-03-22 18:52 UTC, kylerchin commented
What's the difference between this way and the flatpack way?

2021-03-22 22:10 UTC, kylerchin commented
I'm not sure about the stability of the flatpak way and imo the Mojang supported way should be preferred since it's more supported by the developers. Open to input about it :)

2021-03-23 14:49 UTC, kolgza commented
Well, my rationale for favoring the Flatpak version is that it's just easier for new users, and it's better to instruct new users to use the easier method.

I think we need some more outside input on this topic.

2021-06-11 21:27 UTC, jaxsnjohnson commented
Hi, @kylerchin

I would love to work with you on expanding this article!  I was going to be writing an updated article with the wisdom I have learned hosting servers over the last 6 years.  I would love to work with you on it and I love the changes you have made.  LMK if you are interested in collaborating. 

_JJ - Sys76 Happiness Engineer_

2021-06-20 01:40 UTC, kylerchin commented
> Hi, @kylerchin
> 
> I would love to work with you on expanding this article!  I was going to be writing an updated article with the wisdom I have learned hosting servers over the last 6 years.  I would love to work with you on it and I love the changes you have made.  LMK if you are interested in collaborating. 
> 
> _JJ - Sys76 Happiness Engineer_

Hi JJ! I would love to help! How do we start?

2021-06-22 19:52 UTC, jaxsnjohnson commented
If you use Discord you are welcome to reach out to me here: `jaxsnjohnson#5416`

2021-08-18 21:24 UTC, jaxsnjohnson approved these changes
This looks good to me.

2021-08-18 22:19 UTC, storyaddict requested changes
Couple of small formatting requests.

2021-08-18 22:19 UTC, storyaddict commented on _articles/install-minecraft.md
> +If you downloaded a prevew version, the file name will start with `preview_`, so run `java -jar Downloads/preview_Optifine_version_number.jar` instead.
typo: preview

2021-08-18 22:19 UTC, storyaddict commented on _articles/install-minecraft.md
> +If you downloaded a prevew version, the file name will start with `preview_`, so run `java -jar Downloads/preview_Optifine_version_number.jar` instead.
```bash
java -jar Downloads/preview_Optifine_version_number.jar
```

2021-11-03 22:06 UTC, storyaddict commented
@kylerchin please rebase and make my requested changes, then we can merge! :)

2022-03-19 17:38 UTC, garnerlogan65 commented
Minecraft and other gaming articles should be more distinct from informational articles. Perhaps we could edit the site to promote social initiatives under the community section.

2022-03-29 18:23 UTC, gangwerz commented
Closing for now. The conversation seems to have stalled.

2022-03-29 18:23 UTC, closed without merging