End of the world backups
system76/docs pull request #600
Opened 2021-05-20 16:06 UTC by ahoneybun

This is a start of this article though I wanted to open a PR to start the discussion with @storyaddict to work on this new article.

2021-05-20 16:46 UTC, ahoneybun commented
I added some new content addressing your comments.

2021-05-21 01:39 UTC, storyaddict requested changes

2021-05-21 01:39 UTC, storyaddict commented on _articles/disaster-recovery.md
> +Now that we have our data and a clean install of the OS let's prepare so that we will be ready if this issue happens again using our backup article [here](/articles/backup-files).
Sentence adjustments:

Now that we have our data, and a clean install of the OS, let's prepare for if this issue happens again. It's good practice to set up scheduled backups. Our backup article can help:

2021-06-11 19:09 UTC, storyaddict requested changes
please see latest commit :)

2021-06-11 19:49 UTC, ahoneybun commented
Commit? What changes do we need to do or add?

2021-06-11 22:52 UTC, storyaddict approved these changes
Changes look good!

2021-06-11 22:55 UTC, merged