Update list of open firmware models to add gaze15
system76/docs pull request #670
Opened 2021-06-15 21:19 UTC by ids1024

Also use an asterisk to mark which models originally shipped with proprietary firmware.  This seems better than listing them out and
distinguishes the darp6, with had open firmware but proprietary EC, from the others.

2021-06-15 21:33 UTC, jackpot51 approved these changes

2021-06-16 14:43 UTC, ahoneybun requested changes

2021-06-16 14:46 UTC, jacobgkau commented on content/open-firmware-systems.md
> +\* These models shipped with closed firmware/EC, but have since been updated to Open Firmware/EC. [This article](/articles/transition-firmware) can be used to move your system from closed to Open Fir
Given "this" is the pronoun, does that pattern make sense?

2021-06-16 20:39 UTC, ahoneybun approved these changes

2021-06-16 21:11 UTC, merged