Update documentation Pop 21.04 Part One
system76/docs pull request #675
Opened 2021-06-17 15:45 UTC by ahoneybun

This PR updates most of our articles about the 21.04 release of Pop though others will be updated in another PR.

2021-06-17 16:28 UTC, ahoneybun commented
Right now we're waiting for Carl about the Release Notes article.

2021-06-17 23:01 UTC, storyaddict requested changes

2021-06-17 23:01 UTC, storyaddict commented on archived/Pop!_OS-Release-Notes.md
>    - 20.04
add 21.04

2021-06-23 22:42 UTC, storyaddict approved these changes
Main changes look good.

2021-06-23 23:11 UTC, merged