Linux gaming article
system76/docs pull request #688
Opened 2021-06-18 21:45 UTC by ahoneybun

This PR adds a replacement article for the Steam article and also adds sections for GameHub and Lutris. It goes over installing those tools and using them to a degree which can be updated with more content later on.

2021-06-18 21:56 UTC, jackpot51 commented on content/linux-gaming.md
> +apt search steam
Should this be lutris instead?

2021-06-18 21:56 UTC, jackpot51 commented on content/linux-gaming.md
> +![Pop!_Shop Steam](/images/linux-gaming/pop-shop_gamehub.png)
Should the alt text be GameHub?

2021-06-18 22:02 UTC, ahoneybun commented on content/linux-gaming.md
> +![Pop!_Shop Steam](/images/linux-gaming/pop-shop_gamehub.png)
Fixed.

2021-06-18 22:02 UTC, ahoneybun commented on content/linux-gaming.md
> +apt search steam
Fixed.

2021-06-18 22:37 UTC, ids1024 commented
I suppose it would help to have some explanation of what `Lutris` and `GameHub` are and why one would want them? Or Steam, but that should be familiar to people who are already familiar with gaming on Windows.

2021-06-19 00:00 UTC, storyaddict requested changes
We need to flesh out the "installing .exe" section. 

Also we need to explain more about Lutris and/or the differences between Lutris and Gamehub.

Should also highlight open-source games.

2021-06-19 00:02 UTC, ahoneybun commented
Yea I was working on that before I left the office.

2021-06-21 16:37 UTC, ahoneybun commented
@jackpot51 do you know how to fix the conflict? Their commands won't work since we can't push to master without a PR and the steam article is removed with this PR.

2021-06-21 16:50 UTC, storyaddict approved these changes
Updated.

2021-06-21 17:31 UTC, merged