Update install-pop.md
system76/docs pull request #846
Opened 2021-11-26 05:34 UTC by LTTForumCustomizer

Added NVIDIA ISO note at the bottom of guide.

2021-12-06 19:34 UTC, storyaddict requested changes

2021-12-06 19:34 UTC, storyaddict commented on content/install-pop.md
> +
Please format as:

**NOTE:** If you used the ISO with NVIDIA drivers included, this step is not required.


You may also need to rebase to make sure the branch is up to date. :)

2021-12-06 19:36 UTC, leviport commented
Wouldn't this note be redundant because of the sentence on line 85?

2022-03-18 19:56 UTC, jacobgkau commented
I can no longer edit this file because @LTTForumCustomizer has deleted their branch that this PR was coming from.

I don't agree that a note needs to be labeled as a note, but I do agree that this one isn't strictly necessary, although I don't think it would hurt either. In any case, I'm closing this since it can't be modified further; a new PR is welcome to add the additional clarification sentence if anyone else thinks it's needed.

2022-03-18 19:56 UTC, closed without merging